apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesnginx
  namespace: kubernetesnginx-ns
  labels:
    app: kubernetesnginx
    team: devops
  annotations:
    description: sedang belajar kubernetes dengan nginx deployment
    aplikasi: menampilkan index html dengan nginx
spec:
  replicas: 3
  selector:
     matchExpressions:
        - key: app
          operator: In
          values:
            - kubernetesnginx
        - key: env
          operator: In
          values:
            - development
            - devops
            - qa
#    matchLabels:
#      app: kubernetesnginx #match label ini harus sama dengan label template
  template:
    metadata:
      labels:
        app: kubernetesnginx
        env: development
    spec:
      containers:
        - name: kubernetesnginx
          image: joelsipayung/nginxku:v1
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5 #pertama kali kalau melakukan pengecekan menunggu seberapa lama (default 0)
            periodSeconds: 2 #periode pengecekan (default 10)
            timeoutSeconds: 1 #timeout nya berapa lama, misalnya balikannya lebih dari 1 second maka dianggap tidak sehat (default 1)
            successThreshold: 1 #tadinya tdk sehat dan di cek ternyata sehat(mau berapa kali di anggap sehat) (default 1)
            failureThreshold: 4 #berapa kali dianggap tidak sehat dan harus di restart  (default 3) 

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetesnginx
  namespace: kubernetesnginx-ns
  labels:
    app: kubernetesnginx #samadengan label pod
spec:
  type: NodePort
  selector:
    app: kubernetesnginx
  ports:
  - name: http
    port: 8080
    targetPort: 80
#    NodePort: 30001

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubernetesnginx-ingress
  namespace: kubernetesnginx-ns
  labels:
    app: kubernetesnginx
spec:
  rules:
    - host: kubernetesnginx.joelverdy.com
      http:
        paths:
          - path: /service
            backend:
              serviceName: kubernetesnginx # harus sama dengan nama service nya
              servicePort: 8080 # sama dengan port service
